export const UK_UNIVERSITIES = [
  'Anglia Ruskin University',
  'Aston University',
  'Bangor University',
  'University of Bath',
  'Bath Spa University',
  'University of Bedfordshire',
  'University of Birmingham',
  'Birmingham City University',
  'University of Bolton',
  'Bournemouth University',
  'University of Bradford',
  'University of Brighton',
  'University of Bristol',
  'Brunel University London',
  'University of Buckingham',
  'University of Cambridge',
  'Canterbury Christ Church University',
  'Cardiff Metropolitan University',
  'Cardiff University',
  'University of Central Lancashire',
  'University of Chester',
  'University of Chichester',
  'City, University of London',
  'Coventry University',
  'Cranfield University',
  'University for the Creative Arts',
  'University of Cumbria',
  'De Montfort University',
  'University of Derby',
  'University of Dundee',
  'Durham University',
  'University of East Anglia',
  'University of East London',
  'Edge Hill University',
  'University of Edinburgh',
  'University of Essex',
  'University of Exeter',
  'University of Glasgow',
  'Glasgow Caledonian University',
  'University of Gloucestershire',
  'University of Greenwich',
  'Harper Adams University',
  'Heriot-Watt University',
  'University of Hertfordshire',
  'University of Huddersfield',
  'University of Hull',
  'Imperial College London',
  'Keele University',
  'University of Kent',
  'King\'s College London',
  'Kingston University',
  'University of Lancaster',
  'University of Leeds',
  'Leeds Arts University',
  'Leeds Beckett University',
  'Leeds Trinity University',
  'University of Leicester',
  'University of Lincoln',
  'University of Liverpool',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'University of London',
  'London Business School',
  'London Metropolitan University',
  'London School of Economics and Political Science',
  'London South Bank University',
  'Loughborough University',
  'University of Manchester',
  'Manchester Metropolitan University',
  'Middlesex University',
  'Newcastle University',
  'University of Northampton',
  'Northumbria University',
  'Norwich University of the Arts',
  'University of Nottingham',
  'Nottingham Trent University',
  'Open University',
  'University of Oxford',
  'Oxford Brookes University',
  'University of Plymouth',
  'University of Portsmouth',
  'Queen Margaret University',
  'Queen Mary University of London',
  'Queen\'s University Belfast',
  'University of Reading',
  'Regent\'s University London',
  'University of Roehampton',
  'Royal Holloway, University of London',
  'University of Salford',
  'University of Sheffield',
  'Sheffield Hallam University',
  'University of South Wales',
  'University of Southampton',
  'University of St Andrews',
  'St George\'s, University of London',
  'University of Stirling',
  'University of Strathclyde',
  'University of Suffolk',
  'University of Sunderland',
  'University of Surrey',
  'University of Sussex',
  'Swansea University',
  'Teesside University',
  'University of the Arts London',
  'University of the West of England',
  'University of the West of Scotland',
  'Ulster University',
  'University College London',
  'University of Warwick',
  'University of West London',
  'University of Westminster',
  'University of Winchester',
  'University of Wolverhampton',
  'University of Worcester',
  'University of York',
  'York St John University',
];
